[phases.setup]
aptPkgs = ["...", "python3", "ffmpeg"]

[phases.install]
cmds = [
    "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
    "chmod a+rx /usr/local/bin/yt-dlp"
]
